version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: "unless-stopped"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 7
    network_mode: "bridge"

  api:
    container_name: kinvo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:6500:6500
    command: bash -c 'gunicorn --bind 0.0.0.0:6500 wsgi:app'
    restart: "unless-stopped"
    stop_grace_period: "3s"
    environment:
      - WORKDIR=/code
      - DATABASE_URL=postgresql://postgres:postgres@172.17.0.1:5432/postgres
    depends_on:
      - db
    network_mode: "bridge"

volumes:
  postgres_data:
